# 命令执行根目录，此处可以为空，为空会被替换为 one-click-executor.dir
dir: D:\Projects\shineyoung\sy-fts-front
# shell文件路径
shellPath: classpath:component\file\exec-pull-web.sh
# 执行编码，避免日志输出乱码
charset: "utf-8"
# 日志错误关键词（判断是否命令是否成功执行）
errorLogWords: ["abort", "error", "fail", "unable", "Could not"]