# 命令执行根目录，此处可以为空，为空会被替换为 one-click-executor.dir
dir:
# shell文件路径
#shellPath: classpath:component\file\exec-file.sh
shellPath: classpath:component\file\exec-file-zyj.sh
# 执行编码，避免日志输出乱码
charset: "gbk"
# 日志错误关键词（判断是否命令是否成功执行）
errorLogWords: ["abort", "error", "fail", "unable", "Could not"]