# 日志错误关键词（判断是否命令是否成功执行）
errorLogWords: ["abort", "error", "fail", "unable", "Could not"]
# 启用id
enableRefId: [
    "umc3.15",
]
# 模块参数
modulesProperties: [
{
    refId: "server",
    # 远程仓库名称
    remoteRepoName: "origin",
    # 命令执行根目录，此处可以为空，为空会被替换为 one-click-executor.dir
    dir: D:\Projects\shineyoung,
    # 是否需要切换到本地分支
    enableCheckoutLocalBranch: false,
    # 模块参数
    modulesParams: [
    {
        name: "server",
        # 本地分支
        localBranch: "dev",
        # 远程分支
        remoteBranch: ["dev"]
    }
    ]
}
]



