# 命令执行根目录，此处可以为空，为空会被替换为 one-click-executor.dir
dir: D:\Projects\shineyoung\sy-fts
# 日志错误关键词（判断是否命令是否成功执行）
errorLogWords: ["abort", "error", "fail", "unable", "Could not"]
# 启用替换id
enableRefId: [
      "server",
]
# 替换配置文件相对地址
filePaths: [
  sy-fts-gateway/src/main/resources/application.yml,
  sy-fts-system/sy-fts-system-service/src/main/resources/application.yml,
  sy-fts-wcs/sy-fts-wcs-service/src/main/resources/application.yml,
  sy-fts-wms/sy-fts-wms-service/src/main/resources/application.yml,

#  sy-fts-system/sy-fts-system-service/src/main/resources/application-dev-hc.yml,
#  sy-fts-wcs/sy-fts-wcs-service/src/main/resources/application-dev-hc.yml,
#  sy-fts-wms/sy-fts-wms-service/src/main/resources/application-dev-hc.yml
]
# 配置项map，优先级最高
propertiesMap: {
  "spring.profiles.active":"xm-hc",
  "xxl.job.admin.addresses":"http://172.18.16.104:9091/xxl-job-admin"
}
# 需要注释的配置项，优先级最高
uselessProperties: [
]
# 替换关键字描述
replaceKeys: [
  {
    # web环境配置
    refId: "server",
    propertiesMap: {
    }
  }
]

